### ISSUE TITLE
using harfbuzz in application with threads fails to link

### ISSUE THREAD

**Issue by malytomas** [emscripten-ports/HarfBuzz#1]
I want to use harfbuzz in an application with threads. Unfortunately, I am getting this error.
Is this an issue in how harfbuzz is built or am I doing something wrong?

Repository with minimal code to reproduce the issue:
https://github.com/malytomas/em_harf_pthr

Error message:
```
wasm-ld: error: 'atomics' feature is disallowed by hb-buffer_4b5d0574.cc.o, so --shared-memory must not be used
```

Command line:
```bash
em++  -s WASM=1 -s USE_PTHREADS=1 -s USE_ZLIB=1 -s USE_LIBPNG=1 -s USE_LIBJPEG=1 -s USE_FREETYPE=1 -s USE_HARFBUZZ=1 -s ASSERTIONS=1   CMakeFiles/em_harf_pthr.dir/main.cpp.o  -o em_harf_pthr.html
```

**Comment by ebraminio** [comment]
Haven't played with emscripten for some time and don't have the setup here, for now just am adding here pthread support in HarfBuzz needs HAVE_PTHREAD to be passed to HarfBuzz build script probably from here https://github.com/emscripten-core/emscripten/blob/incoming/tools/ports/harfbuzz.py

btw have a look at https://github.com/horizon-games/three-text-renderer which is based https://github.com/harfbuzz/harfbuzzjs

**Comment by kripken** [comment]
Does harfbuzz use threads optionally? If it does then I guess we need to add support for that like we do in the SDL2 port, yeah, passing pthreads to the configure/make process. (If it doesn't, though, then this error is surprising.)

**Comment by ebraminio** [comment]
> Does harfbuzz use threads optionally?

Yes, very subtle use for static things that's why it is optional. It brings it own integration if HAVE_PTHREAD is passed to its build.

**Comment by kripken** [comment]
Thanks! Ok, then we need something like this in emscripten,
```diff
diff --git a/tools/ports/harfbuzz.py b/tools/ports/harfbuzz.py
index 9478f9552..7a20a4de1 100644
--- a/tools/ports/harfbuzz.py
+++ b/tools/ports/harfbuzz.py
@@ -16,6 +16,7 @@ def get(ports, settings, shared):
 
   ports.fetch_project('harfbuzz', 'https://github.com/harfbuzz/harfbuzz/releases/download/' +
                       TAG + '/harfbuzz-' + TAG + '.tar.bz2', 'harfbuzz-' + TAG, is_tarbz2=True, sha512hash=HASH)
+  libname = ports.get_lib_name('harfbuzz' + ('-mt' if settings.USE_PTHREADS else ''))
 
   def create():
     logging.info('building port: harfbuzz')
@@ -29,7 +30,7 @@ def get(ports, settings, shared):
     freetype_include = os.path.join(freetype_dir, 'include')
     freetype_include_dirs = freetype_include + ';' + os.path.join(freetype_include, 'config')
 
-    shared.Building.configure([
+    configure_args = [
       'cmake',
       '-B' + dest_path,
       '-H' + source_path,
@@ -38,11 +39,16 @@ def get(ports, settings, shared):
       '-DFREETYPE_INCLUDE_DIRS=' + freetype_include_dirs,
       '-DFREETYPE_LIBRARY=' + freetype_lib,
       '-DHB_HAVE_FREETYPE=ON'
-    ])
+    ]
+
+    if settings.USE_PTHREADS:
+      configure_args += ['-DHB_HAVE_PTHREAD=ON']
+
+    shared.Building.configure(configure_args)
     shared.Building.make(['make', '-j%d' % shared.Building.get_num_cores(), '-C' + dest_path, 'install'])
     return os.path.join(dest_path, 'libharfbuzz.a')
 
-  return [shared.Cache.get('libharfbuzz.a', create, what='port')]
+  return [shared.Cache.get(libname, create, what='port')]
 
 
 def clear(ports, shared):
```
However it doesn't recognize `-DHB_HAVE_PTHREAD=ON` (or `-DHAVE_PTHREAD=ON`). I don't see it in CMakeLists.txt, how should I pass that in?

**Comment by ebraminio** [comment]
> However it doesn't recognize -DHB_HAVE_PTHREAD=ON (or -DHAVE_PTHREAD=ON). I don't see it in CMakeLists.txt, how should I pass that in?

You can pass `-DCMAKE_CXX_FLAGS="-DHAVE_PTHREAD"` to the build and it should work AFAIK. You probably are right that there should be some other way also. Also please update HarfBuzz to a more recent version if is possible and sorry that I don't have emscripten development setup around so can upload the patch myself (and providing one is somehow how, considering my net limitations). Thank you.

**Comment by kripken** [comment]
Thanks, oddly that didn't work though. I experimented some more and found that `-DCMAKE_CXX_FLAGS="-pthread"` does work, and opened a PR with that! https://github.com/emscripten-core/emscripten/pull/9826
